# Generated by Django 5.1 on 2024-08-31 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('idmascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesados', to='adopcion.mascota')),
            ],
        ),
    ]
